// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrefgqQ3jiucwvqtv09iUcg0W3JzkzslI',
    appId: '1:531556915658:web:3cdcd908afbff48d5b1733',
    messagingSenderId: '531556915658',
    projectId: 'tech-interview-dd80b',
    authDomain: 'tech-interview-dd80b.firebaseapp.com',
    storageBucket: 'tech-interview-dd80b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0myjmsBfLVbDUciZpjE6VWrnzEph6wbY',
    appId: '1:531556915658:android:84866a7d03afddd65b1733',
    messagingSenderId: '531556915658',
    projectId: 'tech-interview-dd80b',
    storageBucket: 'tech-interview-dd80b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Ig1xp8gdOH0p423pustr4CFgUrIHB2w',
    appId: '1:531556915658:ios:2718965dbd86b11b5b1733',
    messagingSenderId: '531556915658',
    projectId: 'tech-interview-dd80b',
    storageBucket: 'tech-interview-dd80b.firebasestorage.app',
    iosBundleId: 'com.example.itemstorage',
  );
}
